######################################################################
# Automatically generated by qmake (2.01a) ?? 18. ??? 15:20:11 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS	 = print_monitor \
           tEditor \
           auth_net_server \
           net_plugin \
           gs_plugin \
           auth_plugin \
           tmpl_sql_plugin

