#!/bin/sh

SPOOL_DIR="/var/spool/cups/tmp"; 
if test "$#" -lt "5"; then
        echo "ERROR: Number of arguments ($#) is wrong" 1>&2
        exit 1
fi
 
if test "$#" -gt "6"; then
        echo "ERROR: Number of arguments ($#) is wrong" 1>&2
        exit 1
fi

jobID=$1;
userName=$2;
jobTitle=$3;
copies=$4;
printFile=$5;

`/opt/filter/pg_check.pl`
RETVAL=$?
#echo $RETVAL;
if test "$RETVAL" != 0; then 
    echo "ERROR: Can't connect to DB $RETVAL";
    `echo /usr/bin/lprm -P ${PRINTER} $1`;
    exit 1;
fi
 
# Get the last parameter (which is the filename if present)
eval filename="\${$#}"
 
if [ -e $filename ]; then
  FILE_TO_PRINT=$filename;
else
  FILE_TO_PRINT="";
fi
 
if [ -z $FILE_TO_PRINT ]; then
  FILE_TO_PRINT=`mktemp -q "$SPOOL_DIR"/audit2ps.XXXXXX`
  if [ $? -ne 0 ]; then
    echo "ERROR: Can't create temp file in $FILE_TO_PRINT \n exiting..." 1>&2
    exit 1
  fi
  trap "rm -f $FILE_TO_PRINT" EXIT SIGHUP SIGINT SIGQUIT SIGABRT SIGTERM 
  cat >$FILE_TO_PRINT
fi
 
if  [ -n $FILE_TO_PRINT ]; then
  cat $FILE_TO_PRINT
  pdfFile=$SPOOL_DIR/${PRINTER}_${1}.pdf
  /usr/bin/psselect -p1 $FILE_TO_PRINT | /usr/bin/ps2pdf - $pdfFile
  #cat $FILE_TO_PRINT | /opt/filter/spts_audit.pl ${PRINTER} $jobID $userName $jobTitle $copies $pdfFile
  #RETVAL=$?
  RETVAL=0;
  if test "$RETVAL" != 0; then 
	echo "ERROR: Can't parsing job file for JOB ${PRINTER}-$jobID \n Return value $RETVAL" 1>&2;
	`echo /usr/bin/lprm -P ${PRINTER} $jobID`;
	exit 1;
  fi
fi


#PRINTER="net_ps";
#echo "x-audit:log $*" >>/tmp/777;
#echo "x-audit:log /usr/sbin/cupsdisable ${PRINTER}"  >>/tmp/777;
#echo "x-audit:log /usr/bin/lprm -P ${PRINTER} $1"  >>/tmp/777;
#echo "x-audit:log /usr/sbin/cupsenable ${PRINTER}"  >>/tmp/777;

#`/usr/sbin/cupsdisable ${PRINTER}`;
#`/usr/bin/lprm -P ${PRINTER} $1`;
#`/usr/sbin/cupsenable ${PRINTER}`;

exit 0;
