######################################################################
# Automatically generated by qmake (1.07a) Wed Jan 26 11:14:15 2011
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
