
//! [0]
/* Add C includes here */

#if defined __cplusplus
/* Add C++ includes here */
#include <QAction>                                
#include <QApplication>                           
#include <QButtonGroup>                           
#include <QColor>                                 
#include <QColorDialog>                           
#include <QComboBox>                              
#include <QCoreApplication>                       
#include <QDataStream>                            
#include <QDate>                                  
#include <QDateTime>                              
#include <QDebug>                                 
#include <QDesktopWidget>                         
#include <QDialog>                                
#include <QDir>                                   
#include <QDrag>                                  
#include <QFile>                                  
#include <QFont>                                  
#include <QFontDialog>                            
#include <QFontMetrics>                           
#include <QFormLayout>                            
#include <QFrame>                                 
#include <QGraphicsRectItem>                      
#include <QGraphicsScene>                         
#include <QGraphicsSceneContextMenuEvent>         
#include <QGraphicsView>                          
#include <QGridLayout>                            
#include <QGroupBox>                              
#include <QHBoxLayout>                            
#include <QHeaderView>                            
#include <QImage>                                 
#include <QInputDialog>                           
#include <QLabel>                                 
#include <QLibrary>                               
#include <QLineEdit>                              
#include <QMainWindow>                            
#include <QMap>                                   
#include <QMapIterator>                           
#include <QMenu>                                  
#include <QMessageBox>                            
#include <QMimeData>                              
#include <QObject>                                
#include <QPainter>                               
#include <QPen>                                   
#include <QPixmap>                                
#include <QPlainTextEdit>                         
#include <QPluginLoader>                          
#include <QPoint>                                 
#include <QPrintDialog>                           
#include <QPrinter>                               
#include <QPrinterInfo>                    
#include <QProcess>                        
#include <QPushButton>                     
#include <QRadioButton>                    
#include <QRegExp>                         
#include <QScrollArea>                     
#include <QSettings>                       
#include <QSignalMapper>                   
#include <QStandardItemModel>              
#include <QStatusBar>                      
#include <QString>                         
#include <QStringList>                     
#include <QStringListModel>                
#include <QtDebug>                         
#include <QTemporaryFile>                  
#include <QTextStream>                     
#include <QThread>                         
#include <QToolButton>                     
#include <QtPlugin>                        
#include <QUuid>                           
#include <QVariant>                        
#include <QVBoxLayout>                     
#include <QWidget>                         
#include <stdio.h>                         
#include <windows.h>                       
#endif 
