######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 07:57:34 2009
######################################################################

TEMPLATE = app
TARGET =new_edge 
DEPENDPATH += . src ui
INCLUDEPATH += .
QT += console core gui network

# Input
HEADERS += src/new_edge.h
FORMS += ui/new_edge.ui
SOURCES += src/main.cpp src/new_edge.cpp
